version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=schedule
      - DB_USER=admin
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - demo

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=schedule
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d  # автоматическая инициализация
    networks:
      - demo

volumes:
  postgres_data:

networks:
  demo:
    driver: bridge
