version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=schedule_db
      - DB_USER=postgres
      - DB_PASSWORD=crfrfkmcrbq
      - DB_PORT=5432
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=schedule_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=crfrfkmcrbq
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 